### ISSUE TITLE
未过滤"忙碌(DND)角色"信息

### ISSUE THREAD

**Issue by tty228** [wind-addons/WindChatFilter#6]
魔兽世界版本：11.0.2（56647）
插件版本：1.5.9
频道：大脚世界频道
信息：“[20:39] [世] [忙碌] [竹簱帮贡饶]： 【3oh】   1--8 全--通 来 大@哥~~”

是否默认规则不会对自定义频道生效？如果想要手动创建规则的话，怎么操作？

![image](https://github.com/user-attachments/assets/83da307e-ba95-4164-9f9b-3d12283f03de)

**Comment by fang2hou** [comment]
DND玩家在世界频道发言算世界频道，不算 DND 频道。看你是国服，那么这个得走 大脚世界频道 的屏蔽规则。
手动创建的话，直接创建就行了，只是因为汉字中间夹带防屏蔽字符的话基本没办法。技术上虽然可以做到，但不可能针对所有消息去做这个识别的，对普通聊天的性能影响很大。

**Comment by tty228** [comment]
> DND玩家在世界频道发言算世界频道，不算 DND 频道。看你是国服，那么这个得走 大脚世界频道 的屏蔽规则。 手动创建的话，直接创建就行了，只是因为汉字中间夹带防屏蔽字符的话基本没办法。技术上虽然可以做到，但不可能针对所有消息去做这个识别的，对普通聊天的性能影响很大。

我是想自己创建一个规则，在 大脚世界频道 中屏蔽 DND 角色，但找不到相关的设置项，使用玩家信息中的自定义玩家名称吗？
还是这只是一个内建的规则，没法自行创建类似的
这些夹带防屏蔽字符的信息太难写关键词了

**Comment by fang2hou** [comment]
> > DND玩家在世界频道发言算世界频道，不算 DND 频道。看你是国服，那么这个得走 大脚世界频道 的屏蔽规则。 手动创建的话，直接创建就行了，只是因为汉字中间夹带防屏蔽字符的话基本没办法。技术上虽然可以做到，但不可能针对所有消息去做这个识别的，对普通聊天的性能影响很大。
> 
> 我是想自己创建一个规则，在 大脚世界频道 中屏蔽 DND 角色，但找不到相关的设置项，使用玩家信息中的自定义玩家名称吗？ 还是这只是一个内建的规则，没法自行创建类似的 这些夹带防屏蔽字符的信息太难写关键词了

因为我游戏内没有遇到过 DND 状态的人在其他频道发言的，我说实话不知道如何识别他们，所以目前是没有这个选项的。
非私有频道（世界频道本质是私有频道）下，DND 状态是有专门事件的，所以非世界频道应该都能识别出来。

**Comment by tty228** [comment]
好的，感谢
